// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlbIDquMpZs78Y5212IZhjTXwva-vGf0A',
    appId: '1:1051084283871:web:e11421632c96074f76ee6a',
    messagingSenderId: '1051084283871',
    projectId: 'shop-wise-f9d93',
    authDomain: 'shop-wise-f9d93.firebaseapp.com',
    storageBucket: 'shop-wise-f9d93.appspot.com',
    measurementId: 'G-F5NCCJL2KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAib9Wba7sdk6jhiiit1lfb4aPjKTDLKlA',
    appId: '1:1051084283871:android:a5c581c1e0a7de1f76ee6a',
    messagingSenderId: '1051084283871',
    projectId: 'shop-wise-f9d93',
    storageBucket: 'shop-wise-f9d93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybejss-at8NDVihCOYEePtbiBJdrYTwE',
    appId: '1:1051084283871:ios:2c44d42c4f3b31ca76ee6a',
    messagingSenderId: '1051084283871',
    projectId: 'shop-wise-f9d93',
    storageBucket: 'shop-wise-f9d93.appspot.com',
    iosBundleId: 'com.example.shopwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAybejss-at8NDVihCOYEePtbiBJdrYTwE',
    appId: '1:1051084283871:ios:432997c09b71fdce76ee6a',
    messagingSenderId: '1051084283871',
    projectId: 'shop-wise-f9d93',
    storageBucket: 'shop-wise-f9d93.appspot.com',
    iosBundleId: 'com.example.shopwise.RunnerTests',
  );
}
